apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins-controller-kubernetes:1.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
          resources:
            requests:
              cpu: "500m"     # Request 0.5 CPU
              memory: "1Gi"   # Request 1GB RAM
            limits:
              cpu: "1000m"    # Limit to 1 CPU
              memory: "2Gi"   # Limit to 2GB RAM
      volumes:
        - name: jenkins-home
          emptyDir: {}
